### PR TITLE
Add hubspot integration

### PR DESCRIPTION
**Pull request by nimrod-codota**
Add a new integration for HubSpot Reporting & Analytics. Roughly following hotjar integration implementation. Since there's no standard for where the HS JS is stored across regions and portals, I have set the entire URL from which the integration fetches the script as the configuration variable.

### CODE REVIEW

**Comment by woopstar** [comment]
+1 on this one. Would love to test it if needed @addisonschultz 

You can provide me access to it like on the Mouseflow integration

**Comment by nimrod-codota** [comment]
hi @addisonschultz, saw your email on some necessary changes here. Will you be able to merge this after I enact the requested changes?

**Comment by nimast** [comment]
@addisonschultz so you copy pasted my code and created your own pr? is this the way gitbook manages its community contributions?

**Comment by addisonschultz** [comment]
Apologies @nimast - I’d like to merge in your original contributions to the updated branch. Apologies for the mis-interpretation, there were some added changes we’d have liked to be included with the original PR, which I should have made on top of this branch.

**Comment by nimast** [comment]
thanks @addisonschultz! I appreciate it. I changed the base of this PR to your branch and merged it in so we don't have conflicts. Seems there are no outstanding changes except taking the commits from here. Please let me know if there's anything else I can do to support getting this merged. Thanks!

**Comment by addisonschultz** [comment]
Thanks again - and apologies for the miscommunication / direction! We’d like to make just a few more tweaks to it before we put it live. But thank you for your contribution, it’s greatly appreciated!

**Comment by gjj** [comment]
Was this integration removed?

**Comment by addisonschultz** [comment]
@gjj you can install it at: https://app.gitbook.com/integrations/gitbook-hubspot

**Comment by gjj** [comment]
> @gjj you can install it at: https://app.gitbook.com/integrations/gitbook-hubspot

Screenshot 2026-05-26 at 3 08 27 PM

Thanks because for some reason searching HubSpot here doesn't bring up anything. That link worked.

**Pull request merged**
