### PR TITLE
GitHub unfurl integration

### PR DESCRIPTION
**Pull request by MTipps**
Github users can now paste a link to either a permalink or a file, and the code will unfurl.

Note: there is still a bit to be done regarding private repos.

### CODE REVIEW

**Review by addisonschultz — APPROVED** [review]

**Review by addisonschultz — APPROVED** [review]

**Comment by bguiz** [comment]
@addisonschultz now that it's merged, is it already usable on gitbook.com automatically? or do I need to opt in or change some config to allow this integration in my space/ collection?

**Comment by bguiz** [comment]
We're running into oauth issues for enabling this integrations in our workspace, getting  5XX error:

gitbook integrations oauth error for github-unfurl

This happens when we visit https://app.gitbook.com/o/-LuC734MpqlgwA6zyhAO/integrations/github-unfurl (that's the URL with our org ID substituted in).

Is there another way for us to enable this?

cc @simi-hedera + @theekrystallee who are admins.

**Comment by addisonschultz** [comment]
Hey @bguiz, apologies. 

Can you use: https://app.gitbook.com/o/-LuC734MpqlgwA6zyhAO/integrations/github-files instead? We migrated this right before we launched it live! 

You can uninstall the one called Unfurl GitHub, and use the link above to install the live/main one.

**Comment by bguiz** [comment]
The new URL worked - we've got it working now - thanks!

Feature requests:
- Add syntax highlighting
- Add toggle for filename visibility


(I'll file github issues for these)

**Comment by bguiz** [comment]
here are the feature requests:

- https://github.com/GitbookIO/integrations/issues/178
- https://github.com/GitbookIO/integrations/issues/179

**Comment by addisonschultz** [comment]
Thanks! I'll have a look and see what we can do 😄

**Pull request merged**
